version: "3.1"

services:
  app:
    image: app-i
    build:
      context: ./client
    container_name: app-c
    ports:
      - "3000:3000"
    volumes:
      - /app:/client/
      - /app/node_modules
